[project]
name = "deflake"
version = "0.1.0"
description = ""
authors = [
    {name = "Deniz Ariyan",email = "denizariyan@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
]

[tool.poetry]
packages = [{include = "deflake", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
