name: Release

on:
  push:
    branches: [main]

concurrency:
  group: "release"
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Place holder workflow
      - name: Hello World
        run: echo "Hello, World!"
